class GamesList {
  static const List<String> games = [
    'PUBG Mobile', 'Free Fire', 'Call of Duty Mobile', 'Mobile Legends: Bang Bang',
    'Genshin Impact', 'Clash of Clans', 'Clash Royale', 'Fortnite', 'Valorant',
    'League of Legends', 'League of Legends: Wild Rift', 'Brawl Stars', 'Roblox',
    'Minecraft', 'Among Us', 'Apex Legends Mobile', 'Arena of Valor', 'Asphalt 9',
    'Candy Crush Saga', 'Clash of Clans', 'Coin Master', 'FIFA Mobile', 'Fortnite',
    'Garena Free Fire', 'Genshin Impact', 'Honkai Star Rail', 'Honor of Kings',
    'League of Legends', 'Lords Mobile', 'Marvel Snap', 'Mobile Legends: Bang Bang',
    'Modern Combat 5', 'PUBG Mobile', 'Pokémon GO', 'Rise of Kingdoms', 'Rocket League',
    'Standoff 2', 'State of Survival', 'Stumble Guys', 'Subway Surfers', 'Summoners War',
    'Teamfight Tactics', 'Tower of Fantasy', 'World of Tanks Blitz', 'Zombie Survival',
    'Dota 2', 'Counter-Strike 2', 'GTA V', 'GTA Online', 'Red Dead Redemption 2',
    'Minecraft Java', 'Minecraft Bedrock', 'Terraria', 'Rust', 'ARK: Survival Evolved',
    'Overwatch 2', 'Warzone', 'Modern Warfare', 'Black Ops', 'Battlefield',
    'FIFA 24', 'eFootball', 'NBA 2K', 'Madden NFL', 'Rocket League',
    'World of Warcraft', 'Final Fantasy XIV', 'Lost Ark', 'New World', 'Elder Scrolls Online',
    'Diablo Immortal', 'Diablo IV', 'Path of Exile', 'Destiny 2', 'Warframe',
    'Fall Guys', 'Roblox', 'Grounded', 'Valheim', 'Sea of Thieves',
    'Fire Emblem Heroes', 'AFK Arena', 'Raid: Shadow Legends', 'Star Wars Galaxy of Heroes',
    'Marvel Contest of Champions', 'DC Legends', 'Injustice 2 Mobile', 'Mortal Kombat Mobile',
    'Real Racing 3', 'Asphalt 8', 'CarX Street', 'Need for Speed No Limits',
    'Township', 'Hay Day', 'Farmville', 'Homescapes', 'Gardenscapes',
    'Dragon City', 'Monster Legends', 'Empires & Puzzles', 'Guardian Tales',
    'Epic Seven', 'Seven Deadly Sins', 'One Piece Bounty Rush', 'Naruto Blazing',
    'Dragon Ball Legends', 'My Hero Academia: The Strongest Hero', 'Bleach: Brave Souls',
    'Wild Rift', 'Identity V', 'Ragnarok Origin', 'Lineage 2M', 'Black Desert Mobile',
    'Rise of Empires', 'Age of Origins', 'Puzzles & Survival', 'Last Shelter: Survival',
    'World War Heroes', 'Modern Ops', 'Sniper 3D', 'Cover Fire',
    'Other',
  ];
}
