const API='https://api.finbassshamar.online';
const state={page:'home',login:true,user:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function token(){return localStorage.getItem('auth_token')}
async function api(path,{method='GET',body,auth=true}={}){const h={'Content-Type':'application/json'};if(auth&&token())h.Authorization='Bearer '+token();const r=await fetch(API+path,{method,headers:h,body:body?JSON.stringify(body):undefined});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||d.error||'Request failed');return d}
async function upload(file){const fd=new FormData();fd.append('file',file);const r=await fetch(API+'/upload',{method:'POST',headers:token()?{Authorization:'Bearer '+token()}: {},body:fd});return r.json()}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function setAuth(login){state.login=login;$('#loginTab').classList.toggle('sel',login);$('#registerTab').classList.toggle('sel',!login);$('#nameWrap').classList.toggle('hidden',login);$('#authSubmit').textContent=login?'Login':'Create account';$('#authMsg').textContent=''}
$('#loginTab').onclick=()=>setAuth(true);$('#registerTab').onclick=()=>setAuth(false);
$('#authForm').onsubmit=async e=>{e.preventDefault();const msg=$('#authMsg');msg.textContent='';try{if(state.login){const d=await api('/auth/login',{method:'POST',body:{email:$('#email').value,password:$('#password').value},auth:false});if(d.requiresTotp||d.message){msg.textContent=d.message||'Verification code required. Use the OTP flow in the app.';return}if(d.token)localStorage.setItem('auth_token',d.token);else{msg.textContent='Login requires verification. Please complete the OTP step.';return}}else{await api('/auth/register',{method:'POST',body:{email:$('#email').value,password:$('#password').value,displayName:$('#displayName').value},auth:false});msg.textContent='Registration started. Check your email for the verification code.';return}await boot()}catch(err){msg.textContent=err.message}}
$('#logoutBtn').onclick=()=>{localStorage.removeItem('auth_token');state.user=null;$('#app').style.display='none';$('#auth').style.display='grid'};
$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');
$$('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));
async function boot(){if(!token())return;$('#auth').style.display='none';$('#app').style.display='grid';try{state.user=await api('/user/me')}catch{}render();}
function go(p){state.page=p;$('.sidebar').classList.remove('open');$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));render()}
function shell(title,sub,html){$('#pageTitle').textContent=title;$('#pageSub').textContent=sub;$('#content').innerHTML='<div class="content">'+html+'</div>'}
async function render(){const p=state.page;const titles={home:['Home','Buy & sell game accounts safely'],listings:['Listings','Browse accounts and marketplace offers'],favorites:['Favorites','Your saved listings'],wallet:['Wallet','Balance, deposits and withdrawals'],orders:['Orders','Purchases and sales'],tournaments:['Tournaments','Join and manage tournaments'],notifications:['Notifications','Account activity and updates'],profile:['Profile','Manage your account'],settings:['Settings','Security and preferences']};const [t,s]=titles[p];shell(t,s,'<div class="empty">Loading…</div>');try{if(p==='home')return home();if(p==='listings')return listings();if(p==='favorites')return favorites();if(p==='wallet')return wallet();if(p==='orders')return orders();if(p==='tournaments')return tournaments();if(p==='notifications')return notifications();if(p==='profile')return profile();return settings()}catch(e){shell(t,s,`<div class="empty"><b>Could not load this page</b><br><span class="small">${esc(e.message)}</span></div>`)}}
async function home(){let d;try{d=await api('/listings')}catch(e){d=[]}const arr=Array.isArray(d)?d:(d.listings||d.data||[]);shell('Home','Buy & sell game accounts safely',`<div class="hero"><div><span class="pill">MYGame Marketplace</span><h2>Level up your collection.</h2><p>Discover game accounts, make offers, chat with sellers and manage purchases from one place.</p></div><button class="primary" onclick="go('listings')">Browse listings</button></div><div class="section"><div class="section-head"><h3>Featured listings</h3><button class="outline" onclick="go('listings')">View all</button></div><div class="grid">${arr.slice(0,8).map(card).join('')||'<div class="empty">No listings available right now.</div>'}</div></div>`)}
function card(x){const title=x.title||x.name||x.game||'Game account';const price=x.price??x.amount??'-';return `<div class="card listing-card"><div class="thumb">🎮</div><div class="row between"><span class="pill">${esc(x.game||'Game')}</span><span class="small">${esc(x.location||'')}</span></div><b>${esc(title)}</b><div class="row between"><span class="price">${esc(price)}</span><button class="outline" onclick="viewListing('${esc(x.id||x._id||'')}')">View</button></div></div>`}
async function listings(){let d=await api('/listings');let arr=Array.isArray(d)?d:(d.listings||d.data||[]);shell('Listings','Browse accounts and marketplace offers',`<div class="section-head"><h3>${arr.length} listings</h3><button class="primary" onclick="toast('Create listing flow uses /listings POST')">+ Sell account</button></div><div class="grid">${arr.map(card).join('')||'<div class="empty">No listings found.</div>'}</div>`)}
async function viewListing(id){if(!id)return;try{const x=await api('/listings/'+id);shell(x.title||'Listing','Listing details',`<div class="card"><div class="thumb">🎮</div><h2>${esc(x.title||x.name||'Game account')}</h2><p class="muted">${esc(x.description||'')}</p><div class="row between"><span class="price">${esc(x.price??'-')}</span><button class="primary" style="width:auto" onclick="toast('Use the purchase/order endpoint from the app flow')">Continue</button></div></div>`)}catch(e){toast(e.message)}}
async function favorites(){const d=await api('/favorites');const arr=Array.isArray(d)?d:(d.favorites||d.data||[]);shell('Favorites','Your saved listings',`<div class="grid">${arr.map(card).join('')||'<div class="empty">No favorites yet.</div>'}</div>`)}
async function wallet(){const [b,t]=await Promise.all([api('/wallet/balance'),api('/wallet/transactions')]);const tx=Array.isArray(t)?t:(t.transactions||t.data||[]);shell('Wallet','Balance, deposits and withdrawals',`<div class="stat-grid"><div class="stat"><span class="small">Available balance</span><b>${esc(b.balance??b.amount??'0')}</b></div><div class="stat"><span class="small">Transactions</span><b>${tx.length}</b></div><div class="stat"><span class="small">Deposit methods</span><b>→</b></div><div class="stat"><span class="small">Withdraw</span><b>→</b></div></div><div class="section"><div class="section-head"><h3>Recent transactions</h3><button class="outline" onclick="toast('Top up uses /wallet/topup')">Top up</button></div><div class="table"><div class="table-row"><b>Description</b><b>Amount</b><b>Status</b><b>Date</b></div>${tx.slice(0,15).map(x=>`<div class="table-row"><span>${esc(x.description||x.type||'Transaction')}</span><span>${esc(x.amount??'-')}</span><span class="success">${esc(x.status||'completed')}</span><span class="small">${esc(x.createdAt||'')}</span></div>`).join('')||'<div class="empty">No transactions.</div>'}</div></div>`)}
async function orders(){const [p,s]=await Promise.all([api('/orders/my-purchases'),api('/orders/my-sales')]);const a=Array.isArray(p)?p:(p.orders||p.data||[]),b=Array.isArray(s)?s:(s.orders||s.data||[]);shell('Orders','Purchases and sales',`<div class="stat-grid"><div class="stat"><span class="small">Purchases</span><b>${a.length}</b></div><div class="stat"><span class="small">Sales</span><b>${b.length}</b></div><div class="stat"><span class="small">Offers</span><b>→</b></div><div class="stat"><span class="small">Vault</span><b>🔒</b></div></div><div class="section"><h3>My purchases</h3><div class="grid">${a.slice(0,8).map(card).join('')||'<div class="empty">No purchases.</div>'}</div></div>`)}
async function tournaments(){const d=await api('/tournaments');const a=Array.isArray(d)?d:(d.tournaments||d.data||[]);shell('Tournaments','Join and manage tournaments',`<div class="grid">${a.map(x=>`<div class="card"><span class="pill">Tournament</span><h3>${esc(x.name||x.title||'Tournament')}</h3><p class="small">${esc(x.description||'')}</p><button class="outline" onclick="toast('Registration uses /tournaments/{id}/register')">View / Join</button></div>`).join('')||'<div class="empty">No tournaments available.</div>'}</div>`)}
async function notifications(){const d=await api('/notifications');const a=Array.isArray(d)?d:(d.notifications||d.data||[]);shell('Notifications','Account activity and updates',`<div class="section-head"><h3>Recent</h3><button class="outline" onclick="api('/notifications/mark-all-read',{method:'POST'}).then(()=>toast('All marked read'))">Mark all read</button></div><div class="grid">${a.map(x=>`<div class="card"><b>${esc(x.title||'Notification')}</b><p class="small">${esc(x.message||x.body||'')}</p></div>`).join('')||'<div class="empty">You are all caught up.</div>'}</div>`)}
async function profile(){const u=state.user||await api('/user/me');state.user=u;shell('Profile','Manage your account',`<div class="card"><div class="row"><div class="avatar">${esc((u.displayName||u.name||u.email||'U')[0].toUpperCase())}</div><div><h2 style="margin:0">${esc(u.displayName||u.name||'User')}</h2><span class="small">${esc(u.email||'')}</span></div></div><div class="section"><div class="stat-grid"><div class="stat"><span class="small">Verification</span><b>${esc(u.verified?'Verified':'—')}</b></div><div class="stat"><span class="small">Account</span><b>Active</b></div><div class="stat"><span class="small">Favorites</span><b>♡</b></div><div class="stat"><span class="small">Security</span><b>2FA</b></div></div></div></div>`)}
function settings(){shell('Settings','Security and preferences',`<div class="grid"><div class="card"><h3>Security</h3><p class="small">Change password, email, TOTP and account security.</p><button class="outline" onclick="toast('Security screens use the auth/user endpoints from the APK')">Manage security</button></div><div class="card"><h3>Notifications</h3><p class="small">Manage notification preferences.</p><button class="outline" onclick="api('/notifications/preferences').then(x=>toast('Preferences loaded'))">Load preferences</button></div><div class="card"><h3>Language</h3><p class="small">The mobile app includes Sinhala, Tamil and English localization.</p><button class="outline" onclick="toast('Language selector can be connected to your localization JSON')">Change language</button></div></div>`)}
window.go=go;window.viewListing=viewListing;window.api=api;
boot();
